import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import HeaderWrapper from "@/components/header-wrapper";
import { auth, currentUser } from "@clerk/nextjs/server";
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme-provider";
import { User as UserType } from "@/types";
import { addUser } from "@/actions/users";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const { userId } = await auth(); // Server-side logic
    const user = await currentUser();
    console.log("User ID:", userId);
    if (userId && user) {
        const userObj: UserType = {
            clerkUserId: userId,
            email: user.emailAddresses[0]?.emailAddress || "",
            firstName: user.firstName || "",
            lastName: user.lastName || "",
            imageUrl: user.imageUrl || "",
        }
        const res = await addUser(userObj);
        console.log("User added:", res);
    }
    return (
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ClerkProvider>
                <html lang="en">
                    <body className="antialiased relative overflow-y-auto">
                        <HeaderWrapper brandName="DoTheTodo" userId={userId} />
                        <main>{children}</main>
                        <Toaster />
                    </body>
                </html>
            </ClerkProvider>
        </ThemeProvider>
    );
}