import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import HeaderWrapper from "@/components/header-wrapper";
import { auth } from "@clerk/nextjs/server";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const { userId } = await auth();
    return (
        <ClerkProvider>
            <html lang="en">
                <body className="antialiased">
                    <HeaderWrapper brandName="Task Manager" userId={userId} />
                    <main>{children}</main>
                    <Toaster />
                </body>
            </html>
        </ClerkProvider>
    );
}